services:
  app:
    image: abnerjacobsen/demo-bd-app:dev
    build:
      context: .
      target: app
    environment:
      - ENVIRONMENT=dev
    env_file:
      - dev.env
    volumes:
      - .:/workspaces/demo-bd
    # command: uvicorn demo-bd.api:app --host 0.0.0.0 --port 8000 --reload
    command: ["api", "--dev"]

  dozzle:
      image: amir20/dozzle:latest
      restart: always
      environment:
        DOZZLE_LEVEL: debug
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8088:8080
      profiles:
        - app
        - dev


